### ISSUE TITLE
Recipe for root6?

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/root5-feedstock#11]
Hi all, I'm wondering if the maintainers of this feedstock have any info on plans for a root6 package in conda-forge? Either on whether this is in the works, or planned at all, or just whether it would be much work for an outsider like me to put together?

**Comment by giacomov** [comment]
In principle it is not complicated, but unfortunately the build time is an issue: conda-forge builds are capped by the free-tier maximum duration of Travis and Circle CI jobs. In my experiments `root6` requires more than that to build, even with a minimal set of options.

I guess one way would be to split into `root6-core` and then various options built on top of that, but that is more work than I can do right now. 

If you want to give it a shot, go ahead! The root5 recipe should be a good starting point.

**Comment by duncanmmacleod** [comment]
Thanks @giacomov, I'll have a stab at merging the root5 recipe and the root6 macports config, and will see what I get to. I'll also talk to the conda-forge core team about build times if that does become an issue.
