### ISSUE TITLE
Archive this feedstock

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root5-feedstock#23]
It's been about 5 years since ROOT 5 was maintained and conda-forge has had a `root` feedstock as of the beginning of 2019 which provides ROOT 6.

As a result, I propose archiving this feedstock. Any thoughts @conda-forge/root5?

**Comment by giacomov** [comment]
Unfortunately there are still projects in the AstroParticle community that didn't migrate yet, afaik. Looping in @grburgess and @henrikef

**Comment by henrikef** [comment]
Thanks @giacomov! I let the HAWC people know as well. I believe that the 3ML analysis framework https://github.com/threeML/threeML and some of its plug-ins, e.g. https://github.com/threeML/hawc_hal, are in the process of migrating to root6 but currently still rely on the root5 feedstock.

**Comment by chrisburr** [comment]
Thanks for the quick response, that makes total sense!
