### ISSUE TITLE
Conda install does not select the latest build

### ISSUE THREAD

**Issue by giacomov** [conda-forge/root5-feedstock#3]
@conda-forge/core : I have made build number 2 of the package, fixing some dependency (in particular, pinning `readline`). The relative pull request was merged and built fine, and indeed the package is where it is supposed to be:

https://anaconda.org/conda-forge/root5/files

However, `conda install -c conda-forge root5` still selects build 0:

```
    root5:            5.34.36-py27_0   conda-forge
```

why is that? Why are build 1 and 2 ignored? I would expect `conda install` to select the latest build...

**Comment by giacomov** [comment]
@isuruf sorry to bother you directly, but I got no answer here and this is becoming a real problem. 

How can I make `conda install` select the latest build automatically?

In alternative, how can I remove an existing build from the `conda-forge` channel so that the replacement gets selected?

**Comment by ericdill** [comment]
Hi @giacomov -- I suspect that the unpinned readline build is being picked up preferentially by the conda solver. Let me label build 0 as "broken" on anaconda.org which effectively render it invisible to the conda solver

**Comment by giacomov** [comment]
Thanks! That indeed fixed it. Now `conda install` selects build 3.

For the future, is there a way I can mark a build as broken, should it happen again in the future? Or do I need to ask an admin such as yourself to do it?

Thanks!

**Comment by ericdill** [comment]
Hi @giacomov --

Yay! I'm glad this is working for you now.

Labeling packages as broken is, for the forseeable future, an admin-only feature. Other avenues to get our attention would be the gitter channel https://gitter.im/conda-forge/conda-forge.github.io

**Comment by giacomov** [comment]
ok, thanks. Closing this now.
